//! Generation of per-account hledger CSV rules files.
//!
//! The generated file is *standard hledger rules syntax* and the user owns
//! it after generation: edit freely, it is never rewritten. The starter file
//! contains a small neutral seed mapping, and a catch-all that sends
//! everything unmatched to `expenses:other` — review replaces that, and each
//! fix added to the rules file makes the next import smarter.
//!
//! Semantics note: in hledger CSV rules, later matching assignments win, so
//! the catch-all is written *first* and the specific `if` blocks follow.

use std::path::Path;

use anyhow::Result;

use crate::config::AccountConfig;

/// Small, neutral, UK-centric seed table: (regex-on-description, account2).
/// Intentionally generic — personal mappings belong in the user's rules file.
///
/// hledger matchers are case-insensitive by default and use POSIX ERE
/// (regex-tdfa): no `(?i)` flags, no lookaheads. "Later rule wins", so
/// more specific mappings must come *after* broader ones (e.g. plain Uber
/// → transport is listed before Uber Eats → delivery).
const SEEDS: &[(&str, &str)] = &[
    ("uber|bolt|lyft", "expenses:transport"),
    ("uber ?eats|deliveroo|just ?eat", "expenses:foods:delivery"),
    (
        "tesco|sainsbury|asda|aldi|lidl|morrisons|waitrose|iceland|co-?op",
        "expenses:groceries",
    ),
    (
        "netflix|spotify|disney|prime video",
        "expenses:subscriptions:entertainment",
    ),
    ("amazon|ebay", "expenses:shopping"),
    ("shell|esso|texaco|bp pulse|bp connect", "expenses:car:fuel"),
];

pub fn rules_path(config_dir_rules: &Path, account: &AccountConfig) -> std::path::PathBuf {
    config_dir_rules.join(format!("{}.rules", account.name))
}

pub fn generate_starter(account: &AccountConfig) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "# hledger CSV rules for account '{}' — generated by bank2hledger.\n\
         # This is standard hledger rules syntax; edit freely, bank2hledger never rewrites it.\n\
         # Reference: https://hledger.org/hledger.html#csv-rules\n\n\
         # The staging CSV has columns: date, description, amount, currency, id\n\
         fields date, description, amount, currency, id\n\n\
         date-format %Y-%m-%d\n\
         currency %currency\n\n\
         # The bank side of every posting in this file:\n\
         account1 {}\n\n\
         # Record the bank's transaction id as a tag for exact dedup.\n\
         comment bank2hledger-id:%id\n\n",
        account.name, account.hledger_account
    ));

    // Catch-all first: later (more specific) matching blocks override it.
    out.push_str(
        "# Catch-all: anything not matched below lands here for review.\n\
         account2 expenses:other\n\n",
    );

    out.push_str("# --- category mappings: regex on description → expense account ---\n");
    for (pattern, acct) in SEEDS {
        out.push_str(&format!("if\n{pattern}\n  account2 {acct}\n\n"));
    }
    out
}

pub fn ensure_rules_file(rules_dir: &Path, account: &AccountConfig) -> Result<std::path::PathBuf> {
    let path = rules_path(rules_dir, account);
    if !path.exists() {
        std::fs::create_dir_all(rules_dir)?;
        std::fs::write(&path, generate_starter(account))?;
    }
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn acct(name: &str, hledger: &str) -> AccountConfig {
        AccountConfig {
            name: name.into(),
            profile: "monzo_csv".into(),
            hledger_account: hledger.into(),
            generic: None,
        }
    }

    #[test]
    fn starter_binds_account1_and_staging_columns() {
        let out = generate_starter(&acct("m", "assets:bank:m"));
        assert!(out.contains("account1 assets:bank:m"), "{out}");
        assert!(out.contains("fields date, description, amount, currency, id"));
        assert!(out.contains("date-format %Y-%m-%d"));
        assert!(out.contains("comment bank2hledger-id:%id"));
    }

    #[test]
    fn catch_all_comes_before_specific_blocks() {
        // hledger: later matching assignments win, so the catch-all must be
        // written first and the if-blocks after it.
        let out = generate_starter(&acct("m", "assets:bank:m"));
        let catch_all = out.find("account2 expenses:other").unwrap();
        let first_if = out.find("\nif\n").unwrap();
        assert!(
            catch_all < first_if,
            "catch-all must precede if-blocks:\n{out}"
        );
    }

    #[test]
    fn every_seed_regex_is_ere_safe() {
        // hledger uses POSIX ERE (regex-tdfa): (?i) flags and lookarounds
        // would be generated as broken rules. Guard against future edits.
        for (pattern, _) in SEEDS {
            assert!(
                !pattern.contains("(?i"),
                "inline flags unsupported: {pattern}"
            );
            assert!(
                !pattern.contains("(?=") && !pattern.contains("(?!"),
                "lookarounds unsupported: {pattern}"
            );
            assert!(
                !pattern.contains("(?<"),
                "lookbehind unsupported: {pattern}"
            );
        }
    }

    #[test]
    fn uber_eats_is_mapped_after_uber() {
        // "later wins": for "UBER EATS" both patterns match, so delivery must
        // appear after transport in the generated file.
        let out = generate_starter(&acct("m", "assets:bank:m"));
        let transport = out.find("uber|bolt|lyft").unwrap();
        let delivery = out.find("uber ?eats").unwrap();
        assert!(transport < delivery);
    }

    #[test]
    fn ensure_creates_missing_file_and_is_idempotent() {
        let dir = tempfile::tempdir().unwrap();
        let rules_dir = dir.path().join("rules");
        let a = acct("test-acct", "assets:bank:test");
        let p1 = ensure_rules_file(&rules_dir, &a).unwrap();
        assert!(p1.exists());
        let p2 = ensure_rules_file(&rules_dir, &a).unwrap();
        assert_eq!(p1, p2);
        assert_eq!(rules_dir.join("test-acct.rules"), p1);
    }

    #[test]
    fn user_edits_are_never_overwritten() {
        let dir = tempfile::tempdir().unwrap();
        let rules_dir = dir.path().join("rules");
        std::fs::create_dir_all(&rules_dir).unwrap();
        let a = acct("test-acct", "assets:bank:test");
        let path = rules_dir.join("test-acct.rules");
        std::fs::write(&path, "# my precious hand-written rules\nfields date\n").unwrap();
        ensure_rules_file(&rules_dir, &a).unwrap();
        assert_eq!(
            std::fs::read_to_string(&path).unwrap(),
            "# my precious hand-written rules\nfields date\n"
        );
    }

    #[test]
    fn rules_path_uses_account_name() {
        assert_eq!(
            rules_path(Path::new("/r"), &acct("monzo-personal", "x")),
            Path::new("/r").join("monzo-personal.rules")
        );
    }
}
